Allow setting password for user without password
If user does not have rep:password code fails with:
Caused by NoMethodError: undefined method `match' for nil:NilClass
/var/chef/cache/cookbooks/cq/libraries/provider_cq_user.rb:246:in `hash_decoder'
/var/chef/cache/cookbooks/cq/libraries/provider_cq_user.rb:268:in `hash_generator'
/var/chef/cache/cookbooks/cq/libraries/provider_cq_user.rb:295:in `password_update?'
/var/chef/cache/cookbooks/cq/libraries/provider_cq_user.rb:70:in `modify_user'

The problem is that ruby evaluates hash_generator(new_pass) before checking if end_with? can be called on nil.